### ISSUE TITLE
remove in tree module as a pre-requisite.

### ISSUE THREAD

**Issue by mregmi** [kubernetes-sigs/kernel-module-management#104]
Hello, Is there a way to tell the KMMO to remove a certain kernel module before we load ours? In a OOT driver we are currently working on, we need to remove the in tree driver before we load ours. Thanks
To elaborate, in order to insert our OOT graphics driver, we first need to remove in tree drm driver or else the insert will fail. if there no current functionality to do this before insert, a way to run a pre-requisite commands/scripts would be a good idea.

**Comment by qbarrand** [comment]
Would an [InitContainer](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) that runs `modprobe -r <list of modules to unload>` be a good solution to this?

**Comment by mregmi** [comment]
InitContainer for kmmo? we can give it a try. Thanks.

**Comment by qbarrand** [comment]
I mean than KMM would generate a module loader DaemonSet that contains such an init container. That means that we would not be able to load the in-tree module again after we unload the OOT one, but at least that would fit your use case.

**Comment by uMartinXu** [comment]
@qbarrand I can't understand the benefits to do it in init-container.  It is for security concern. And you want restrict user to do any operation they want in KMMO like SRO? If so, user also can do what ever they want to do in init-container also can bring the risk.

Before we talking about the security, we need to start from the user/role of the KMMO.  Please correct me. @qbarrand 
1. Cluster-administrators the user who make use of KMMO Module CR to manage drivers in the cluster. As the Cluster-administrators, they should be trusted in some degree. But we can't fully trust him, because they also can make some mistake by accident to impair the cluster. So we need to design KMMO to reduce the chance for the administrators to make this kind of mistake. Actually SeLinux and Linux Smack technology can be used to achieve it.
2. Driver developers/distributors: who develop, package and distribute the driver code and driver container images. Normally they are not in charge of manage the Moule CR in a specific cluster. Their code and packaged binary should be fully trust. Since the driver will be insmod into kernel, and in theory the code can do everything in the kernel. And they have the full knowledge how to build the driver, how to inmod and configure the driver, and also know how sanity check the driver.

So if we agree on these two roles, then, I think it should be Driver developers to provide the process which can be some program or script (static linked binary is preferred). And the program can be packaged into the driver container image for KMMO to insmod and configure the driver. Since this program is from driver developers/distributors, and can be fully trusted. And should not has the security vulnerability.

**Comment by uMartinXu** [comment]
@qbarrand any comments? :)

**Comment by hershpa** [comment]
A few thoughts to get a discussion started. From an implementation point of view, is the plan to call `modprobe -r` in the same preStartHook as modprobe in the moduleLoader container? The prerequisite of having volume `/lib/modules/$KERNEL_FULL_VERSION` being mounted is already taken care of. This step of removing an in-tree module would be the first step done, correct? Where would the user specify that they would like to optionally remove the in-tree module, somewhere in the module CR right? Would KMM assume and take the moduleName we specify to load as the same one we want to unload right? Or would the `moduleNametoRemove` be user configurable as a new field? The latter option gives more flexibility and is worth discussing. We do have a usage case for the latter option currently.

**Comment by qbarrand** [comment]
> is the plan to call modprobe -r in the same [PostStart ](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks)hook as modprobe in the moduleLoader container?

Yes.

> This step of removing an in-tree module would be the first step done, even before copying the firmware files, correct?

I think so, yes.

> Would KMM assume and take the moduleName we specify to load as the same one we want to unload? Or would the `moduleNametoRemove` be user configurable as a new field?

I am in favor of the latter. `modprobe -r` would only be added to the `PostStart` hook when that field is set.
The new fields could look like the following:
```yaml
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: my_mod

        unloadBefore:
          name: my_intree_mod
```

**Comment by hershpa** [comment]
Thanks @qbarrand

**Comment by hershpa** [comment]
That is correct. Thanks @qbarrand
