### ISSUE TITLE
Reduce the TLS granularity configuration to be global per module.

### ISSUE THREAD

**Issue by ybettan** [kubernetes-sigs/kernel-module-management#164]
The more we talk about it the more complex it become.

Currently, the places in which we handle TLS configurations are:
* `moduelLoader.registryTLS`
* `moduleLoader.kernelMappings[].registryTLS`
* `moduleLoader.kernelMappings[].build.baseImageRegistryTLS`
* `moduleLoader.kernelMappings[].sign.unsignedImageRegistryTLS`

Some questions to be considered:
* Where should the `registryTLS` be taken from? the `moduleLoader` or `moduleLoader.kernelMappings[]`? This adds complexity to the code.
* What happens if a user don't specify a build/sign `<base/unsigned>ImageRegistryTLS`? Does it expects it to be the same as the configurations in `moduleLoader[.kernelMappings[]]`)? Or does it expect it to just get the default values?
* How do maintain a minimal diff with m/s? OCP builds is enforcing TLS and allows mounting trusted CAs
    - Does `kaniko` know where to take the trusted CAs from depending on the OS it is running on? Or do we need to mount them?

This issue is for discussion, to understand if we really need to maintain all the options?

It will be much simpler to set a single TLS configuration for the entire module, without deferring between kernel mappings and without differing between the TLS options for accessing images in general or during the build/sign processes.

The proposed solution is:
* Having a single TLS configuration per module
* A user will be able to enable TLS for all access to image registries without granularity, or disable it.
    - Should `enabled` be the default?

Will be happy to get some feedback from the community here about potential usage.

Also would love to get your feedback @yevgeny-shnaidman @qbarrand @chr15p @enriquebelarte @mresvanis

**Comment by qbarrand** [comment]
> Where should the `registryTLS` be taken from? the `moduleLoader` or `moduleLoader.kernelMappings[]`? This adds complexity to the code.

We have the same logic for the `build` and `sign` sections - the mapping's settings take precedence over the global ones.

> What happens if a user don't specify a build/sign `<base/unsigned>ImageRegistryTLS`? Does it expects it to be the same as the configurations in `moduleLoader[.kernelMappings[]])`? Or does it expect it to just get the default values?

Default trust store IMHO.

> How do maintain a minimal diff with m/s? OCP builds is enforcing TLS and allows mounting trusted CAs
> - Does `kaniko` know where to take the trusted CAs from depending on the OS it is running on? Or do we need to mount them?

Kaniko is also enforcing TLS, unless you disable it explicitly.
The Kaniko image [includes Debian's CA certs](https://github.com/GoogleContainerTools/kaniko/blob/main/deploy/Dockerfile#L43-L45). If we wanted to mount custom CAs in the pod, we would have to add a custom field to the CRD and implement the logic in the job manager.
OpenShift Build objects create pods that mount all CAs configured in the cluster automatically.

> The proposed solution is:
> - Having a single TLS configuration per module
> - A user will be able to enable TLS for all access to image registries without granularity, or disable it.
>    - Should `enabled` be the default?

Sounds dangerous to me. I think it's undesirable to entirely disable TLS just because we need to pull once an unsigned image from a self-signed registry.
