### ISSUE TITLE
Helm chart?

### ISSUE THREAD

**Issue by tkatila** [kubernetes-sigs/kernel-module-management#171]
More of a question than an issue, is there helm charts for KMMO? I couldn't find any myself. If not, are there plans?

**Comment by qbarrand** [comment]
Hi @tkatila! No Helm chart so far and no plans for them currently. Why do you need a Helm chart?

**Comment by tkatila** [comment]
Roger, I'd like to have a top level helm chart which would have kmmo (chart) as a dependency. It would allow us to deploy backported driver, device plugin and other dependencies with one command. At least in theory.

**Comment by qbarrand** [comment]
Does [this](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md) look useful? Looks like you would need to have an overlay that has KMM as a base as well as other Helm charts. Never tried it myself, though.
We use kustomize because [controller-gen](https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/controller-gen) is able to generate deployment manifests and CRDs from the code directly. To offer a Helm chart, we would likely need to sync changes by hand.

**Comment by tkatila** [comment]
Thanks for the link! At first glance it would seem to work for us. I'll test it.
